/* tslint:disable */
/* eslint-disable */
/**
 * vResume API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface ResumeCreateDraftDto
 */
export interface ResumeCreateDraftDto {

    /**
     * The job posting to tailor the resume to
     *
     * @type {string}
     * @memberof ResumeCreateDraftDto
     */
    posting: string;

    /**
     * The original resume file to use as a knowledge base
     *
     * @type {Blob}
     * @memberof ResumeCreateDraftDto
     */
    resume: Blob;
}
