/* tslint:disable */
/* eslint-disable */
/**
 * vResume API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface ResumeVersionUpdateDto
 */
export interface ResumeVersionUpdateDto {

    /**
     * The query message of what to update
     *
     * @type {string}
     * @memberof ResumeVersionUpdateDto
     */
    _query: string;

    /**
     * The selected ui nodes to update
     *
     * @type {string}
     * @memberof ResumeVersionUpdateDto
     */
    selected?: string;
}
